---
kind: pipeline
type: docker
name: mxnet-build-ubuntu-cpu-release

platform:
  os: linux
  arch: amd64

node:
  hw: cpu

steps:
- name: fetch-submodules
  image: drone/git
  commands:
  - git submodule update --init --recursive --jobs $(nproc) 
- name: fetch-ccache
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull ${DRONE_STAGE_NAME}





# compile_unix_cpu_openblas
- name: fetch-ccache-unix-cpu-openblas
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull ${DRONE_STAGE_NAME}
- name: build-unix-cpu-openblas
  image: mxnetci/build.ubuntu_cpu
  commands:
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1 USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j16
  - make cython PYTHON=python3
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache-unix-cpu-openblas


# compile_unix_openblas_debug_cpu
- name: fetch-ccache-unix-cpu-openblas-debug
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull unix-cpu-openblas-debug
- name: build-unix-cpu-openblas-debug
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cmake -DUSE_CUDA=OFF -DUSE_TVM_OP=ON -DPython3_EXECUTABLE=/usr/bin/python3 -DUSE_MKL_IF_AVAILABLE=OFF -DUSE_OPENMP=OFF -DUSE_OPENCV=ON -DUSE_SIGNAL_HANDLER=ON -DCMAKE_BUILD_TYPE=Debug -G Ninja .
  - ninja -v
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache-unix-cpu-openblas-debug

# compile_unix_mkl_cpu
- name: fetch-ccache-unix-cpu-mkl
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull unix-cpu-mkl
- name: build-unix-cpu-mkl
  image: mxnetci/build.ubuntu_cpu
  commands:
  - make DEV=1 USE_CPP_PACKAGE=1 USE_BLAS=mkl USE_TVM_OP=1 USE_MKLDNN=0 USE_INTEL_PATH=/opt/intel USE_DIST_KVSTORE=1 USE_SIGNAL_HANDLER=1 -j16
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache-unix-cpu-mkl

# compile_unix_mkldnn_cpu
- name: fetch-ccache-unix-cpu-mkldnn
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull unix-cpu-mkldnn
- name: build-unix-cpu-mkldnn
  image: mxnetci/build.ubuntu_cpu
  commands:
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=openblas USE_SIGNAL_HANDLER=1 -j16
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache-unix-cpu-mkldnn


# compile_unix_mkldnn_mkl_cpu(),
# compile_unix_int64_cpu(),
# compile_unix_openblas_cpu_no_tvm_op(),


- name: build
  image: mxnetci/build.ubuntu_cpu
  commands:
  - set
  - ccache -s
  - ccache --zero-stats
  - make DEV=0 ENABLE_TESTCOVERAGE=0 USE_CPP_PACKAGE=0 USE_MKLDNN=0 USE_BLAS=openblas USE_SIGNAL_HANDLER=1 -j16
  - ccache -s
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache

# test_unix_python3_cpu(),
# test_unix_python3_debug_cpu(),
# test_unix_python3_mkl_cpu(),
# test_unix_python3_mkldnn_cpu(),
# test_unix_python3_mkldnn_mkl_cpu(),
# test_unix_scala_cpu(),
# test_unix_scala_mkldnn_cpu(),
# test_unix_clojure_cpu(),
# test_unix_clojure_integration_cpu(),
# test_unix_perl_cpu(),
# test_unix_r_cpu(),
# test_unix_r_mkldnn_cpu(),
# test_unix_julia07_cpu(),
# test_unix_julia10_cpu(),
# test_unix_onnx_cpu(),
# test_unix_cpp_cpu(),
# test_static_scala_cpu(),
# test_static_python_cpu(),
# test_unix_python3_cpu_no_tvm_op(),


- name: test
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/drone-mxnet-ci:latest
  commands:
  - cd python/
  - pip install -e .
  - cd ..
  - MXNET_TEST_COUNT=1 nosetests --nocapture --verbose tests/python/unittest/test_operator.py:test_norm
  depends_on:
  - build
  - build-unix-cpu-openblas
  - build-unix-cpu-openblas-debug
  - build-unix-cpu-mkl
  - build-unix-cpu-mkldnn
    
#- name: push-ccache
#  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
#  commands:
#  - /bin/cache_sync.sh push cpu
#  depends_on:
#  - build

image_pull_secrets:
- dockerconfigjson

trigger:
  event:
  - pull_request
  - push
  - cron


---
kind: pipeline
type: docker
name: mxnet-build-ubuntu-cpu-mkldnn-release

platform:
  os: linux
  arch: amd64

node:
  hw: cpu

steps:
- name: fetch-submodules
  image: drone/git
  commands:
  - git submodule update --init --recursive --jobs $(nproc) 

- name: fetch-ccache
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull cpu-mkldnn

- name: build
  image: mxnetci/build.ubuntu_cpu
  commands:
  - ccache -s
  - ccache --zero-stats
  - make DEV=0 ENABLE_TESTCOVERAGE=0 USE_CPP_PACKAGE=0 USE_MKLDNN=1 USE_BLAS=openblas USE_SIGNAL_HANDLER=1 -j16
  - ccache -s
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache

- name: push-ccache
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh push cpu-mkldnn
  depends_on:
  - build

image_pull_secrets:
- dockerconfigjson

trigger:
  event:
  - pull_request
  - push


---
kind: pipeline
type: docker
name: mxnet-build-ubuntu-gpu-release

platform:
  os: linux
  arch: amd64

node:
  hw: gpu

steps:
- name: fetch-submodules
  image: drone/git
  commands:
  - git submodule update --init --recursive --jobs $(nproc) 

- name: fetch-ccache
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull gpu

- name: build
  image: mxnetci/build.ubuntu_gpu_cu102
  commands:
  - ccache -s
  - ccache --zero-stats
  - make CUDA_ARCH="-gencode arch=compute_75,code=[sm_75,compute_75] --fatbin-options -compress-all" DEV=0 ENABLE_TESTCOVERAGE=0 USE_CPP_PACKAGE=0 USE_MKLDNN=0 USE_BLAS=openblas USE_SIGNAL_HANDLER=1 USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_DIST_KVSTORE=1 -j16
  - ccache -s
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache

- name: push-ccache
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh push gpu
  depends_on:
  - build

image_pull_secrets:
- dockerconfigjson

trigger:
  event:
  - pull_request
  - push


---
kind: pipeline
type: docker
name: mxnet-build-ubuntu-gpu-mkldnn-release

platform:
  os: linux
  arch: amd64

node:
  hw: gpu

steps:
- name: fetch-submodules
  image: drone/git
  commands:
  - git submodule update --init --recursive --jobs $(nproc) 

- name: fetch-ccache
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh pull gpu-mkldnn

- name: build
  image: mxnetci/build.ubuntu_gpu_cu102
  commands:
  - ccache -s
  - ccache --zero-stats
  - make CUDA_ARCH="-gencode arch=compute_75,code=[sm_75,compute_75] --fatbin-options -compress-all" DEV=0 ENABLE_TESTCOVERAGE=0 USE_CPP_PACKAGE=0 USE_MKLDNN=1 USE_BLAS=openblas USE_SIGNAL_HANDLER=1 USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_DIST_KVSTORE=1 -j16
  - ccache -s
  environment:
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /tmp/ccache
    CCACHE_DIR: /drone/src/.ccache
  depends_on:
  - fetch-submodules
  - fetch-ccache

- name: push-ccache
  image: 120448866817.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci-ccache
  commands:
  - /bin/cache_sync.sh push gpu-mkldnn
  depends_on:
  - build

image_pull_secrets:
- dockerconfigjson

trigger:
  event:
  - pull_request
  - push
  - cron

---
kind: signature
hmac: f8e3b73d28f1cb2bce20cfb256c549b809e24d532d1557cf49a21228110b44d2

...
