---
clone:
  disable: true
kind: pipeline
name: sanity
node:
  hw: cpu
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - mkdir -p src.orig && cd src.orig
  - /usr/local/bin/clone-commit
  - git submodule update --init --recursive
  image: drone/git
  name: clone-src
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j32
  - make cython PYTHON=python3
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: sanity-basic
  image: mxnetci/build.ubuntu_cpu
  name: compile-basic
- commands:
  - cd $${BUILD_DIR}
  - cd python
  - pip install -e .
  - cd ..
  - MXNET_TEST_COUNT=1 nosetests --nocapture --verbose tests/python/unittest/test_operator.py:test_norm
  depends_on:
  - compile-basic
  environment:
    BUILD_DIR: sanity-basic
    MXNET_HOME: sanity-basic/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-basic-python
type: docker
---
clone:
  disable: true
depends_on:
- sanity
kind: pipeline
name: unix-cpu
node:
  hw: cpu
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - mkdir -p src.orig && cd src.orig
  - /usr/local/bin/clone-commit
  - git submodule update --init --recursive
  image: drone/git
  name: clone-src
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j4
  - make cython PYTHON=python3
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-openblas
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas
  environment:
    BUILD_DIR: unix-cpu-openblas
    MXNET_HOME: unix-cpu-openblas/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-python3
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j4
  - make cython PYTHON=python3
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-openblas-debug
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas-debug
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas-debug
  environment:
    BUILD_DIR: unix-cpu-openblas-debug
    MXNET_HOME: unix-cpu-openblas-debug/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-debug-python3
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_BLAS=mkl USE_TVM_OP=1 USE_MKLDNN=0 USE_INTEL_PATH=/opt/intel
    USE_DIST_KVSTORE=1 USE_SIGNAL_HANDLER=1 -j4
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-mkl
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkl
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-mkl
  environment:
    BUILD_DIR: unix-cpu-mkl
    MXNET_HOME: unix-cpu-mkl/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-mkl-python3
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=openblas USE_SIGNAL_HANDLER=1
    -j4
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-mkldnn
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkldnn
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu_mkldnn
  depends_on:
  - compile-mkldnn
  environment:
    BUILD_DIR: unix-cpu-mkldnn
    MXNET_HOME: unix-cpu-mkldnn/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-mkldnn-python3
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=mkl USE_SIGNAL_HANDLER=1 USE_INTEL_PATH=/opt/intel/
    -j4
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-mkldnn-mkl
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkldnn-mkl
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu_mkldnn
  depends_on:
  - compile-mkldnn-mkl
  environment:
    BUILD_DIR: unix-cpu-mkldnn-mkl
    MXNET_HOME: unix-cpu-mkldnn-mkl/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-mkldnn-mkl-python3
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - cmake -DUSE_SIGNAL_HANDLER=ON -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_MKLDNN=OFF
    -DCMAKE_BUILD_TYPE=Release -DUSE_INT64_TENSOR_SIZE=ON -G Ninja
  - ninja -v
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-int64
  image: mxnetci/build.ubuntu_cpu
  name: compile-int64
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-int64
  environment:
    BUILD_DIR: unix-cpu-int64
    MXNET_HOME: unix-cpu-int64/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-int64-python3
- commands:
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - cmake -DUSE_CUDA=OFF -DUSE_TVM_OP=OFF -DPython3_EXECUTABLE=/usr/bin/python3 -DUSE_MKL_IF_AVAILABLE=OFF
    -DUSE_OPENMP=OFF -DUSE_OPENCV=ON -DUSE_SIGNAL_HANDLER=ON -DCMAKE_BUILD_TYPE=Release
    -G Ninja
  - ninja -v
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-openblas-no-tvm-op
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas-no-tvm-op
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas-no-tvm-op
  environment:
    BUILD_DIR: unix-cpu-openblas-no-tvm-op
    MXNET_HOME: unix-cpu-openblas-no-tvm-op/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-no-tvm-op-python3
type: docker
---
kind: signature
hmac: 541094a493fd63ef0176993fc3a3fa6075710e9aa4615552a2cb92d75d7a4747

...
