---
clone:
  disable: true
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: sanity
node:
  hw: cpu
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - mkdir -p src.orig && cd src.orig
  - /usr/local/bin/clone-commit
  - git submodule update --init --recursive
  - cd ..
  - aws s3 sync s3://mxnet-ci-drone-ccache/sanity-ccache /drone/src/ccache --no-progress
    --quiet
  - /ci/setup_build_env.sh
  - ls -liaF && du -hs *
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: clone-src
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j 16
  - make cython PYTHON=python3
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/sanity-basic
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/sanity-basic
    FLAVOR_BUILD_DIR: sanity-basic
  image: mxnetci/build.ubuntu_cpu
  name: compile-basic
- commands:
  - cd $${FLAVOR_BUILD_DIR}
  - pwd && ls -liaF && find . -name libmxnet.so
  - cd python && pip install -e . && cd ..
  - MXNET_TEST_COUNT=1 nosetests --nocapture --verbose tests/python/unittest/test_operator.py:test_norm
  depends_on:
  - compile-basic
  environment:
    FLAVOR_BUILD_DIR: sanity-basic
    MXNET_HOME: /drone/src/sanity-basic
    MXNET_LIBRARY_PATH: /drone/src/sanity-basic/libmxnet.so
  image: mxnetci/build.ubuntu_cpu
  name: test-basic-python
- commands:
  - ls -liaF && du -hs *
  - aws s3 sync /drone/src/ccache s3://mxnet-ci-drone-ccache/sanity-ccache --delete
    --no-progress --quiet
  depends_on:
  - compile-basic
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: build-cleanup
  when:
    status:
    - failure
    - success
type: docker
---
clone:
  disable: true
depends_on:
- sanity
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: unix-cpu
node:
  hw: cpu
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - mkdir -p src.orig && cd src.orig
  - /usr/local/bin/clone-commit
  - git submodule update --init --recursive
  - cd ..
  - aws s3 sync s3://mxnet-ci-drone-ccache/unix-cpu-ccache /drone/src/ccache --no-progress
    --quiet
  - /ci/setup_build_env.sh
  - ls -liaF && du -hs *
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: clone-src
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j4
  - make cython PYTHON=python3
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/unix-cpu-openblas
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-openblas
    FLAVOR_BUILD_DIR: unix-cpu-openblas
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas
- commands:
  - cd $${FLAVOR_BUILD_DIR}
  - pwd && ls -liaF && find . -name libmxnet.so
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas
  environment:
    FLAVOR_BUILD_DIR: unix-cpu-openblas
    MXNET_HOME: /drone/src/unix-cpu-openblas
    MXNET_LIBRARY_PATH: /drone/src/unix-cpu-openblas/libmxnet.so
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j4
  - make cython PYTHON=python3
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/unix-cpu-openblas-debug
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-openblas-debug
    FLAVOR_BUILD_DIR: unix-cpu-openblas-debug
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas-debug
- commands:
  - cd $${FLAVOR_BUILD_DIR}
  - pwd && ls -liaF && find . -name libmxnet.so
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas-debug
  environment:
    FLAVOR_BUILD_DIR: unix-cpu-openblas-debug
    MXNET_HOME: /drone/src/unix-cpu-openblas-debug
    MXNET_LIBRARY_PATH: /drone/src/unix-cpu-openblas-debug/libmxnet.so
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-debug-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_BLAS=mkl USE_TVM_OP=1 USE_MKLDNN=0 USE_INTEL_PATH=/opt/intel
    USE_DIST_KVSTORE=1 USE_SIGNAL_HANDLER=1 -j4
  - make cython PYTHON=python3
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/unix-cpu-mkl
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-mkl
    FLAVOR_BUILD_DIR: unix-cpu-mkl
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkl
- commands:
  - cd $${FLAVOR_BUILD_DIR}
  - pwd && ls -liaF && find . -name libmxnet.so
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-mkl
  environment:
    FLAVOR_BUILD_DIR: unix-cpu-mkl
    MXNET_HOME: /drone/src/unix-cpu-mkl
    MXNET_LIBRARY_PATH: /drone/src/unix-cpu-mkl/libmxnet.so
  image: mxnetci/build.ubuntu_cpu
  name: test-mkl-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=openblas USE_SIGNAL_HANDLER=1
    -j4
  - make cython PYTHON=python3
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/unix-cpu-mkldnn
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-mkldnn
    FLAVOR_BUILD_DIR: unix-cpu-mkldnn
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkldnn
- commands:
  - cd $${FLAVOR_BUILD_DIR}
  - pwd && ls -liaF && find . -name libmxnet.so
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu_mkldnn
  depends_on:
  - compile-mkldnn
  environment:
    FLAVOR_BUILD_DIR: unix-cpu-mkldnn
    MXNET_HOME: /drone/src/unix-cpu-mkldnn
    MXNET_LIBRARY_PATH: /drone/src/unix-cpu-mkldnn/libmxnet.so
  image: mxnetci/build.ubuntu_cpu
  name: test-mkldnn-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=mkl USE_SIGNAL_HANDLER=1 USE_INTEL_PATH=/opt/intel/
    -j4
  - make cython PYTHON=python3
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/unix-cpu-mkldnn-mkl
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-mkldnn-mkl
    FLAVOR_BUILD_DIR: unix-cpu-mkldnn-mkl
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkldnn-mkl
- commands:
  - cd $${FLAVOR_BUILD_DIR}
  - pwd && ls -liaF && find . -name libmxnet.so
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu_mkldnn
  depends_on:
  - compile-mkldnn-mkl
  environment:
    FLAVOR_BUILD_DIR: unix-cpu-mkldnn-mkl
    MXNET_HOME: /drone/src/unix-cpu-mkldnn-mkl
    MXNET_LIBRARY_PATH: /drone/src/unix-cpu-mkldnn-mkl/libmxnet.so
  image: mxnetci/build.ubuntu_cpu
  name: test-mkldnn-mkl-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - cmake -DUSE_SIGNAL_HANDLER=ON -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_MKLDNN=OFF
    -DCMAKE_BUILD_TYPE=Release -DUSE_INT64_TENSOR_SIZE=ON -G Ninja
  - ninja -v -j 4
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/unix-cpu-int64
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-int64
    FLAVOR_BUILD_DIR: unix-cpu-int64
  image: mxnetci/build.ubuntu_cpu
  name: compile-int64
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - ls -liaF
  - . ./drone-build.env
  - set
  - ccache --zero-stats
  - cp -r src.orig $${FLAVOR_BUILD_DIR} && cd $${FLAVOR_BUILD_DIR}
  - cmake -DUSE_CUDA=OFF -DUSE_TVM_OP=OFF -DPython3_EXECUTABLE=/usr/bin/python3 -DUSE_MKL_IF_AVAILABLE=OFF
    -DUSE_OPENMP=OFF -DUSE_OPENCV=ON -DUSE_SIGNAL_HANDLER=ON -DCMAKE_BUILD_TYPE=Release
    -G Ninja
  - ninja -v -j 4
  - ccache -s
  depends_on:
  - clone-src
  environment:
    CCACHE_DIR: /drone/src/ccache/unix-cpu-openblas-no-tvm-op
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-openblas-no-tvm-op
    FLAVOR_BUILD_DIR: unix-cpu-openblas-no-tvm-op
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas-no-tvm-op
- commands:
  - cd $${FLAVOR_BUILD_DIR}
  - pwd && ls -liaF && find . -name libmxnet.so
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas-no-tvm-op
  environment:
    FLAVOR_BUILD_DIR: unix-cpu-openblas-no-tvm-op
    MXNET_HOME: /drone/src/unix-cpu-openblas-no-tvm-op
    MXNET_LIBRARY_PATH: /drone/src/unix-cpu-openblas-no-tvm-op/libmxnet.so
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-no-tvm-op-python3
- commands:
  - ls -liaF && du -hs *
  - aws s3 sync /drone/src/ccache s3://mxnet-ci-drone-ccache/unix-cpu-ccache --delete
    --no-progress --quiet
  depends_on:
  - compile-openblas
  - compile-openblas-debug
  - compile-mkl
  - compile-mkldnn
  - compile-mkldnn-mkl
  - compile-openblas-no-tvm-op
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: build-cleanup
  when:
    status:
    - failure
    - success
type: docker
---
kind: signature
hmac: 45efc81ce00ad27efbcfeab39c38245fb287f60ab8088f1ab80dc8326f3951b0

...
