---
kind: pipeline
type: docker
name: mxnet-build-unix-cpu-release

platform:
  os: linux
  arch: amd64

node:
  hw: cpu

clone:
  disable: true




steps:
- name: clone-src
  image: drone/git
  commands:
  - mkdir -p orig && cd orig
  - /usr/local/bin/clone-commit
  - git submodule update --init --recursive



# compile_unix_cpu_openblas
- name: build-unix-cpu-openblas
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cp -r orig $${BUILD_NAME} && cd $${BUILD_NAME}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1 USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j16
  - make cython PYTHON=python3
  environment:
    BUILD_NAME: unix-cpu-openblas
  depends_on:
  - clone-src


# compile_unix_openblas_debug_cpu
- name: build-unix-cpu-openblas-debug
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cp -r orig $${BUILD_NAME} && cd $${BUILD_NAME}
  - cmake -DUSE_CUDA=OFF -DUSE_TVM_OP=ON -DPython3_EXECUTABLE=/usr/bin/python3 -DUSE_MKL_IF_AVAILABLE=OFF -DUSE_OPENMP=OFF -DUSE_OPENCV=ON -DUSE_SIGNAL_HANDLER=ON -DCMAKE_BUILD_TYPE=Debug -G Ninja .
  - ninja -v
  environment:
    BUILD_NAME: unix-cpu-openblas-debug
  depends_on:
  - clone-src

# compile_unix_mkl_cpu
- name: build-unix-cpu-mkl
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cp -r orig $${BUILD_NAME} && cd $${BUILD_NAME}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_BLAS=mkl USE_TVM_OP=1 USE_MKLDNN=0 USE_INTEL_PATH=/opt/intel USE_DIST_KVSTORE=1 USE_SIGNAL_HANDLER=1 -j16
  environment:
    BUILD_NAME: unix-cpu-mkl
  depends_on:
  - clone-src

# compile_unix_mkldnn_cpu
- name: build-unix-cpu-mkldnn
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cp -r orig $${BUILD_NAME} && cd $${BUILD_NAME}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=openblas USE_SIGNAL_HANDLER=1 -j16
  environment:
    BUILD_NAME: unix-cpu-mkldnn
  depends_on:
  - clone-src


# compile_unix_mkldnn_mkl_cpu(),
# compile_unix_int64_cpu(),
# compile_unix_openblas_cpu_no_tvm_op(),


# test_unix_python3_cpu(),
# test_unix_python3_debug_cpu(),
# test_unix_python3_mkl_cpu(),
# test_unix_python3_mkldnn_cpu(),
# test_unix_python3_mkldnn_mkl_cpu(),
# test_unix_scala_cpu(),
# test_unix_scala_mkldnn_cpu(),
# test_unix_clojure_cpu(),
# test_unix_clojure_integration_cpu(),
# test_unix_perl_cpu(),
# test_unix_r_cpu(),
# test_unix_r_mkldnn_cpu(),
# test_unix_julia07_cpu(),
# test_unix_julia10_cpu(),
# test_unix_onnx_cpu(),
# test_unix_cpp_cpu(),
# test_static_scala_cpu(),
# test_static_python_cpu(),
# test_unix_python3_cpu_no_tvm_op(),


- name: test-unix-python3-cpu
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cd $${BUILD_NAME}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  environment:
    BUILD_NAME: unix-cpu-openblas
  depends_on:
  - build-unix-cpu-openblas

- name: test-unix-python3-debug-cpu
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cd $${BUILD_NAME}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  environment:
    BUILD_NAME: unix-cpu-openblas-debug
  depends_on:
  - build-unix-cpu-openblas-debug

- name: test-unix-python3-mkl-cpu
  image: mxnetci/build.ubuntu_cpu
  commands:
  - cd $${BUILD_NAME}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  environment:
    BUILD_NAME: unix-cpu-mkl
  depends_on:
  - build-unix-cpu-mkl


image_pull_secrets:
- dockerconfigjson

trigger:
  event:
  - pull_request
  - push
  - cron

---
kind: signature
hmac: 8eacba97568e44d7457cd3a9af815e7b6863ca4fd06054c835429caea417ead6

...
