---
clone:
  disable: true
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: sanity
node:
  hw: cpu
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - mkdir -p src.orig && cd src.orig
  - /usr/local/bin/clone-commit
  - git submodule update --init --recursive
  - aws s3 sync s3://mxnet-ci-drone-ccache/sanity-ccache ccache --no-progress --quiet
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: clone-src
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j 16
  - make cython PYTHON=python3
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: sanity-basic
    CCACHE_DIR: /drone/src/ccache/sanity-basic
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/sanity-basic
  image: mxnetci/build.ubuntu_cpu
  name: compile-basic
- commands:
  - cd $${BUILD_DIR}
  - cd python
  - pip install -e .
  - cd ..
  - MXNET_TEST_COUNT=1 nosetests --nocapture --verbose tests/python/unittest/test_operator.py:test_norm
  depends_on:
  - compile-basic
  environment:
    BUILD_DIR: sanity-basic
    MXNET_HOME: sanity-basic/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-basic-python
- commands:
  - aws s3 sync ccache s3://mxnet-ci-drone-ccache/sanity-ccache --delete --no-progress
    --quiet
  depends_on:
  - test-basic-python
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: cleanup
type: docker
---
clone:
  disable: true
depends_on:
- sanity
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: unix-cpu
node:
  hw: cpu
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - mkdir -p src.orig && cd src.orig
  - /usr/local/bin/clone-commit
  - git submodule update --init --recursive
  - aws s3 sync s3://mxnet-ci-drone-ccache/unix-cpu-ccache ccache --no-progress --quiet
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: clone-src
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j2
  - make cython PYTHON=python3
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-openblas
    CCACHE_DIR: /drone/src/ccache/unix-cpu-openblas
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-openblas
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas
  environment:
    BUILD_DIR: unix-cpu-openblas
    MXNET_HOME: unix-cpu-openblas/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_TVM_OP=1 USE_CPP_PACKAGE=1 USE_BLAS=openblas USE_MKLDNN=0 USE_DIST_KVSTORE=1
    USE_LIBJPEG_TURBO=1 USE_SIGNAL_HANDLER=1 -j2
  - make cython PYTHON=python3
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-openblas-debug
    CCACHE_DIR: /drone/src/ccache/unix-cpu-openblas-debug
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-openblas-debug
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas-debug
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas-debug
  environment:
    BUILD_DIR: unix-cpu-openblas-debug
    MXNET_HOME: unix-cpu-openblas-debug/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-debug-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_BLAS=mkl USE_TVM_OP=1 USE_MKLDNN=0 USE_INTEL_PATH=/opt/intel
    USE_DIST_KVSTORE=1 USE_SIGNAL_HANDLER=1 -j2
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-mkl
    CCACHE_DIR: /drone/src/ccache/unix-cpu-mkl
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-mkl
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkl
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-mkl
  environment:
    BUILD_DIR: unix-cpu-mkl
    MXNET_HOME: unix-cpu-mkl/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-mkl-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=openblas USE_SIGNAL_HANDLER=1
    -j2
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-mkldnn
    CCACHE_DIR: /drone/src/ccache/unix-cpu-mkldnn
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-mkldnn
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkldnn
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu_mkldnn
  depends_on:
  - compile-mkldnn
  environment:
    BUILD_DIR: unix-cpu-mkldnn
    MXNET_HOME: unix-cpu-mkldnn/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-mkldnn-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - make DEV=1 USE_CPP_PACKAGE=1 USE_TVM_OP=1 USE_BLAS=mkl USE_SIGNAL_HANDLER=1 USE_INTEL_PATH=/opt/intel/
    -j2
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-mkldnn-mkl
    CCACHE_DIR: /drone/src/ccache/unix-cpu-mkldnn-mkl
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-mkldnn-mkl
  image: mxnetci/build.ubuntu_cpu
  name: compile-mkldnn-mkl
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu_mkldnn
  depends_on:
  - compile-mkldnn-mkl
  environment:
    BUILD_DIR: unix-cpu-mkldnn-mkl
    MXNET_HOME: unix-cpu-mkldnn-mkl/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-mkldnn-mkl-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - cmake -DUSE_SIGNAL_HANDLER=ON -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_MKLDNN=OFF
    -DCMAKE_BUILD_TYPE=Release -DUSE_INT64_TENSOR_SIZE=ON -G Ninja
  - ninja -v -j 2
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-int64
    CCACHE_DIR: /drone/src/ccache/unix-cpu-int64
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-int64
  image: mxnetci/build.ubuntu_cpu
  name: compile-int64
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-int64
  environment:
    BUILD_DIR: unix-cpu-int64
    MXNET_HOME: unix-cpu-int64/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-int64-python3
- commands:
  - mkdir -p $${CCACHE_TEMPDIR} $${CCACHE_DIR}
  - /work/runtime_functions.sh build_ccache_wrappers
  - cp -r src.orig $${BUILD_DIR} && cd $${BUILD_DIR}
  - cmake -DUSE_CUDA=OFF -DUSE_TVM_OP=OFF -DPython3_EXECUTABLE=/usr/bin/python3 -DUSE_MKL_IF_AVAILABLE=OFF
    -DUSE_OPENMP=OFF -DUSE_OPENCV=ON -DUSE_SIGNAL_HANDLER=ON -DCMAKE_BUILD_TYPE=Release
    -G Ninja
  - ninja -v -j 2
  depends_on:
  - clone-src
  environment:
    BUILD_DIR: unix-cpu-openblas-no-tvm-op
    CCACHE_DIR: /drone/src/ccache/unix-cpu-openblas-no-tvm-op
    CCACHE_MAXSIZE: 10G
    CCACHE_TEMPDIR: /drone/src/ccache-tmp/unix-cpu-openblas-no-tvm-op
  image: mxnetci/build.ubuntu_cpu
  name: compile-openblas-no-tvm-op
- commands:
  - cd $${BUILD_DIR}
  - /work/runtime_functions.sh unittest_ubuntu_python3_cpu
  depends_on:
  - compile-openblas-no-tvm-op
  environment:
    BUILD_DIR: unix-cpu-openblas-no-tvm-op
    MXNET_HOME: unix-cpu-openblas-no-tvm-op/python/mxnet
  image: mxnetci/build.ubuntu_cpu
  name: test-openblas-no-tvm-op-python3
- commands:
  - aws s3 sync ccache s3://mxnet-ci-drone-ccache/unix-cpu-ccache --delete --no-progress
    --quiet
  depends_on:
  - test-openblas-python3
  - test-openblas-debug-python3
  - test-mkl-python3
  - test-mkldnn-python3
  - test-mkldnn-mkl-python3
  - test-int64-python3
  - test-openblas-no-tvm-op-python3
  image: 187885003319.dkr.ecr.us-west-2.amazonaws.com/mxnet-ci/buildtools
  name: cleanup
type: docker
---
kind: signature
hmac: 25b8f854960b96cff7be5e4cda555048f2dfd2eafc71b78d8e56f8e77a758266

...
